import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. See the src/ folder for source code.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	bundle: true,
	entryPoints: ["main.ts"],
	external: ["obsidian", "electron", "@codemirror/autocomplete", ...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	platform: "browser",
	outfile: "main.js",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	define: { "process.env.NODE_ENV": prod ? '"production"' : '"development"' },
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
