/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. See the src/ folder for source code.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DSHBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DSH_DIR_NAME = ".dsh";
var INBOX_DIR_NAME = "inbox";
var NO_BASE_PATH_MESSAGE = "\u65E0\u6CD5\u4ECE Obsidian \u63A8\u5BFC\u77E5\u8BC6\u5E93\u6839\u76EE\u5F55\uFF08\u79FB\u52A8\u7AEF\u6216\u53D7\u9650\u73AF\u5883\u4E0D\u652F\u6301\uFF09\uFF0C\u8BF7\u5728\u300C\u8BBE\u7F6E \u2192 DSH Bridge\u300D\u91CC\u624B\u52A8\u586B\u5199\u6536\u4EF6\u7BB1\u76EE\u5F55\u3002";
function detectSeparator(p) {
  const s = String(p == null ? "" : p);
  if (/^[A-Za-z]:[\\/]/.test(s) || /^\\\\/.test(s) || s.indexOf("\\") !== -1)
    return "\\";
  return "/";
}
function stripTrailingSeparators(p) {
  const s = String(p == null ? "" : p);
  if (!s)
    return "";
  if (/^[A-Za-z]:[\\/]*$/.test(s))
    return s.slice(0, 2) + "\\";
  const out = s.replace(/[\\/]+$/, "");
  return out || "/";
}
function joinPath(base, ...parts) {
  const sep = detectSeparator(base);
  let out = stripTrailingSeparators(base);
  for (const part of parts) {
    if (part == null)
      continue;
    const clean = String(part).replace(/^[\\/]+/, "").replace(/[\\/]+$/, "");
    if (!clean)
      continue;
    const seg = clean.split(/[\\/]+/).join(sep);
    if (!out || out === "/")
      out = out + seg;
    else if (/^[A-Za-z]:\\$/.test(out))
      out = out + seg;
    else
      out = out + sep + seg;
  }
  return out;
}
function normalizeVaultPath(p) {
  if (typeof p !== "string")
    return "";
  const s = p.trim();
  if (!s)
    return "";
  return stripTrailingSeparators(s);
}
function getVaultBasePath(app) {
  try {
    const vault = app && app.vault;
    const adapter = vault && vault.adapter;
    let raw = "";
    if (adapter) {
      if (typeof adapter.basePath === "string" && adapter.basePath) {
        raw = adapter.basePath;
      } else if (typeof adapter.getBasePath === "function") {
        raw = adapter.getBasePath();
      }
    }
    if (!raw && vault && typeof vault.getBasePath === "function")
      raw = vault.getBasePath();
    if (!raw && app && typeof app.getBasePath === "function")
      raw = app.getBasePath();
    return normalizeVaultPath(raw);
  } catch (e) {
    return "";
  }
}
function resolveDshInboxDir(app, settings) {
  const override = settings && typeof settings.dshInboxDir === "string" ? settings.dshInboxDir.trim() : "";
  if (override) {
    return { path: override, source: "override", vaultRoot: "", error: "" };
  }
  const vaultRoot = getVaultBasePath(app);
  if (!vaultRoot) {
    return { path: "", source: "none", vaultRoot: "", error: NO_BASE_PATH_MESSAGE };
  }
  return {
    path: joinPath(vaultRoot, DSH_DIR_NAME, INBOX_DIR_NAME),
    source: "derived",
    vaultRoot,
    error: ""
  };
}
var DEFAULT_SETTINGS = {
  // 留空 = 自动推导为 <vault>/.dsh/inbox；仅在需要放到别处时才填写（覆盖值）
  dshInboxDir: "",
  workbenchUrl: "http://127.0.0.1:8777/"
};
var DSHBridgePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
  }
  async onload() {
    try {
      await this.app.vault.adapter.write(".dsh-bridge-debug", "onload-entered: " + new Date().toISOString());
    } catch (e) {
    }
    await this.loadSettings();
    this.warnIfInboxPathUnavailable();
    try {
      const p = ".dsh-bridge-ping";
      if (!await this.app.vault.adapter.exists(p)) {
        await this.app.vault.adapter.write(p, `loaded: ${new Date().toISOString()}
version: 0.1.0
`);
      }
    } catch (e) {
      try {
        await this.app.vault.adapter.write(".dsh-bridge-debug", "ping-error: " + (e && e.message));
      } catch (e2) {
      }
    }
    this.addCommand({
      id: "send-current-note-to-dsh",
      name: "\u628A\u5F53\u524D\u7B14\u8BB0\u9001\u7ED9 DSH \u5904\u7406",
      callback: () => this.sendCurrentNote()
    });
    this.addCommand({
      id: "open-dsh-workbench",
      name: "\u6253\u5F00 DSH Obsidian \u5DE5\u4F5C\u53F0",
      callback: () => {
        window.open(this.settings.workbenchUrl, "_blank");
        new import_obsidian.Notice("\u6B63\u5728\u6253\u5F00\u5DE5\u4F5C\u53F0\u2026\uFF08\u82E5\u672A\u54CD\u5E94\uFF0C\u8BF7\u5148\u5728 DSH \u4E2D\u542F\u52A8\u5DE5\u4F5C\u53F0\u670D\u52A1\uFF09");
      }
    });
    this.addCommand({
      id: "show-vault-stats",
      name: "\u67E5\u770B\u77E5\u8BC6\u5E93\u72B6\u6001",
      callback: () => new VaultStatsModal(this.app).open()
    });
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("\u{1F4DA} " + this.app.vault.getMarkdownFiles().length + " \u7BC7");
    this.addSettingTab(new DSHBridgeSettingTab(this));
  }
  onunload() {
    var _a;
    (_a = this.statusBarItem) == null ? void 0 : _a.remove();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 解析当前生效的收件箱目录（用户覆盖优先，否则从 vault 根推导）
  resolveInboxDir() {
    return resolveDshInboxDir(this.app, this.settings);
  }
  // 推导失败时给出「可见」的错误提示，不静默失败
  warnIfInboxPathUnavailable() {
    const r = this.resolveInboxDir();
    if (r.error) {
      new import_obsidian.Notice("\u26A0\uFE0F DSH Bridge\uFF1A" + r.error, 1e4);
    }
    return r;
  }
  async sendCurrentNote() {
    const view = this.app.workspace.getActiveFile();
    if (!view) {
      new import_obsidian.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u7B14\u8BB0");
      return;
    }
    const resolved = this.resolveInboxDir();
    if (!resolved.path) {
      new import_obsidian.Notice("\u274C " + resolved.error, 1e4);
      return;
    }
    try {
      const content = await this.app.vault.read(view);
      const stamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `${stamp}__${view.basename}.md`;
      const dir = resolved.path.replace(/\\/g, "/");
      const req = window.require;
      if (typeof req !== "function") {
        new import_obsidian.Notice("\u5F53\u524D\u73AF\u5883\u4E0D\u652F\u6301 Node \u6A21\u5757\uFF08\u4EC5\u684C\u9762\u7AEF\u53EF\u7528\uFF09");
        return;
      }
      const fs = req("fs").promises;
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(
        dir + "/" + fileName,
        `---
source: "${view.path}"
sent_at: "${new Date().toISOString()}"
---

${content}
`
      );
      new import_obsidian.Notice(`\u2705 \u5DF2\u9001\u5230 DSH \u6536\u4EF6\u7BB1\uFF1A${fileName}`);
    } catch (e) {
      new import_obsidian.Notice(`\u274C \u53D1\u9001\u5931\u8D25\uFF1A${e.message}`);
    }
  }
};
var VaultStatsModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F4DA} \u77E5\u8BC6\u5E93\u72B6\u6001" });
    const files = this.app.vault.getMarkdownFiles();
    const now = Date.now();
    let totalChars = 0;
    for (const f of files)
      totalChars += f.stat.size;
    const recent7 = files.filter((f) => now - f.stat.mtime < 7 * 864e5).length;
    const lines = [
      `\u7B14\u8BB0\u603B\u6570\uFF1A<b>${files.length}</b>`,
      `\u603B\u5B57\u6570\uFF08\u542B\u6807\u8BB0\uFF09\uFF1A<b>${Math.round(totalChars / 2).toLocaleString()}</b> \u5B57\u7B26\u7EA6`,
      `\u8FD1 7 \u5929\u66F4\u65B0\uFF1A<b>${recent7}</b> \u7BC7`,
      `\u6700\u8FD1\u4FEE\u6539\uFF1A${[...files].sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, 5).map((f) => `\u2022 ${f.path}\uFF08${new Date(f.stat.mtime).toLocaleString()}\uFF09`).join("<br>")}`
    ];
    for (const l of lines)
      contentEl.createEl("p", { text: l, cls: "dsh-bridge-line" });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DSHBridgeSettingTab = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  display(containerEl) {
    containerEl.empty();
    const { Setting } = require("obsidian");
    const resolved = resolveDshInboxDir(this.plugin.app, this.plugin.settings);
    const autoHint = resolved.source === "derived" ? `\u7559\u7A7A = \u81EA\u52A8\u63A8\u5BFC\u4E3A\uFF1A${resolved.path}` : resolved.error || "\u7559\u7A7A = \u81EA\u52A8\u63A8\u5BFC\u4E3A <\u77E5\u8BC6\u5E93>/.dsh/inbox";
    new Setting(containerEl).setName("DSH \u6536\u4EF6\u7BB1\u76EE\u5F55\uFF08\u53EF\u9009\u8986\u76D6\uFF09").setDesc("\u300C\u9001\u7ED9 DSH\u300D\u547D\u4EE4\u628A\u7B14\u8BB0\u590D\u5236\u5230\u7684\u76EE\u5F55\u3002" + autoHint).setPlaceholder(resolved.source === "override" ? "<\u77E5\u8BC6\u5E93>/.dsh/inbox" : resolved.path || "<\u77E5\u8BC6\u5E93>/.dsh/inbox").setTextInput(
      (v) => v.setValue(this.plugin.settings.dshInboxDir).onChange(async (val) => {
        this.plugin.settings.dshInboxDir = val;
        await this.plugin.saveSettings();
      })
    );
    new Setting(containerEl).setName("\u5DE5\u4F5C\u53F0\u5730\u5740").setDesc("\u300C\u6253\u5F00\u5DE5\u4F5C\u53F0\u300D\u547D\u4EE4\u8BBF\u95EE\u7684 URL").setTextInput(
      (v) => v.setValue(this.plugin.settings.workbenchUrl).onChange(async (val) => {
        this.plugin.settings.workbenchUrl = val;
        await this.plugin.saveSettings();
      })
    );
  }
};
module.exports.__dshBridgePaths = {
  DSH_DIR_NAME,
  INBOX_DIR_NAME,
  NO_BASE_PATH_MESSAGE,
  DEFAULT_SETTINGS,
  detectSeparator,
  stripTrailingSeparators,
  joinPath,
  normalizeVaultPath,
  getVaultBasePath,
  resolveDshInboxDir
};
